export enum ErrorCode {
  // AUTH ERRORS (1xxx)
  INVALID_CREDENTIALS = 'AUTH_1001',
  USER_NOT_FOUND = 'AUTH_1002',
  USER_ALREADY_EXISTS = 'AUTH_1003',
  INVALID_TOKEN = 'AUTH_1004',
  TOKEN_EXPIRED = 'AUTH_1005',

  // COUPLE ERRORS (2xxx)
  COUPLE_NOT_FOUND = 'COUPLE_2001',
  USER_ALREADY_IN_COUPLE = 'COUPLE_2002',
  USER_NOT_IN_COUPLE = 'COUPLE_2003',
  COUPLE_ALREADY_EXISTS = 'COUPLE_2004',

  // ACCOUNT ERRORS (3xxx)
  ACCOUNT_NOT_FOUND = 'ACCOUNT_3001',
  ACCOUNT_LIMIT_EXCEEDED = 'ACCOUNT_3002',
  ACCOUNT_BELONGS_TO_ANOTHER_COUPLE = 'ACCOUNT_3003',
  CANNOT_DELETE_ACCOUNT_WITH_BALANCE = 'ACCOUNT_3004',

  // TRANSACTION ERRORS (4xxx)
  TRANSACTION_NOT_FOUND = 'TRANSACTION_4001',
  TRANSACTION_LIMIT_EXCEEDED = 'TRANSACTION_4002',
  INSUFFICIENT_FREE_SPENDING = 'TRANSACTION_4003',
  INVALID_TRANSACTION_AMOUNT = 'TRANSACTION_4004',

  // SUBSCRIPTION ERRORS (5xxx)
  SUBSCRIPTION_NOT_FOUND = 'SUBSCRIPTION_5001',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_5002',
  PLAN_LIMIT_EXCEEDED = 'SUBSCRIPTION_5003',
  PLAN_NOT_FOUND = 'SUBSCRIPTION_5004',

  // INFRASTRUCTURE ERRORS (9xxx)
  DATABASE_ERROR = 'INFRA_9001',
  CACHE_ERROR = 'INFRA_9002',
  TENANT_CONTEXT_NOT_SET = 'INFRA_9003',
  INTERNAL_SERVER_ERROR = 'INFRA_9999',
}
